# Generated by Django 5.0.6 on 2024-05-15 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('processing', 'processing'), ('created', 'created'), ('pending', 'pending'), ('completed', 'completed')], default='created', max_length=20)),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.order')),
                ('urgent_delivery', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.urgentdelivery')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
