# Generated by Django 5.0.6 on 2024-05-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('scheduled_order', 'scheduled_order'), ('delivery', 'delivery')], default='delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'weekly'), ('fortnight', 'fortnight')], default='weekly', max_length=20),
        ),
    ]
