# Generated by Django 5.0.6 on 2024-05-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('processing', 'processing'), ('created', 'created'), ('pending', 'pending'), ('completed', 'completed')], default='created', max_length=20),
        ),
        migrations.AddField(
            model_name='urgentdelivery',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('created', 'created'), ('pending', 'pending'), ('completed', 'completed')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('scheduled', 'scheduled'), ('urgent', 'urgent')], default='urgent', max_length=20),
        ),
    ]
