# Generated by Django 5.0.6 on 2024-05-22 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_urgentdelivery_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='status',
            new_name='order_status',
        ),
    ]
