# Generated by Django 5.0.6 on 2024-05-14 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_order_status_urgentdelivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainence',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintained', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='urgentdelivery',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urgent_delivery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
    ]
