# Generated by Django 5.0.6 on 2024-05-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_status_notification_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urgentdelivery',
            options={'verbose_name_plural': 'Urgent Deliveries'},
        ),
    ]
